apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: dependency-track-dev

resources:
- ../../base

namespace: dependency-track-dev

namePrefix: dev-

commonLabels:
  environment: dev
  
patches:
- path: patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment

replicas:
- name: dependency-track-frontend
  count: 1
- name: dependency-track-backend
  count: 1
- name: dependency-track-database
  count: 1