apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependency-track-dev
resources:
- ../../base

namePrefix: dev-
labels:
- pairs:
    environment: dev

images:
- name: public.ecr.aws/a1x0e8q5/abdu/dt-frontend
  newTag: 3aa9449e
- name: public.ecr.aws/a1x0e8q5/abdu/dt-backend
  newTag: 8d3292d6

patches:
- path: patch.yaml
- path: nginx-config-patch.yaml

secretGenerator:
- name: database-secret
  behavior: replace
  literals:
  - username=dtuser
  - password=dev-password-123

configMapGenerator: # this for all allow restart when config changes
- name: environment-config
  literals:
  - ENVIRONMENT=development
  - LOG_LEVEL=DEBUG
