apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base

namePrefix: dev-
commonLabels:
  environment: dev

images:
- name: public.ecr.aws/a1x0e8q5/abdu/dt-frontend
  newTag: latest
- name: public.ecr.aws/a1x0e8q5/abdu/dt-backend
  newTag: latest

patchesStrategicMerge:
- patch.yaml

secretGenerator:
- name: database-secret
  behavior: replace
  literals:
  - username=dtuser
  - password=dev-password-123

configMapGenerator:
- name: environment-config
  literals:
  - ENVIRONMENT=development
  - LOG_LEVEL=DEBUG