apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track-frontend
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: JAVA_OPTIONS
          value: "-Xmx1g -Xms512m -XX:+UseG1GC"
        - name: ALPINE_DATABASE_URL
          value: "jdbc:postgresql://dev-dependency-track-database:5432/dependencytrack"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
spec:
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data-pvc
spec:
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track-frontend
spec:
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: API_BASE_URL
          value: "http://dev-dependency-track-backend:8080"
