apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track-frontend
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: JAVA_OPTIONS
          value: "-Xmx512m -Xms256m -XX:+UseG1GC"
        - name: ALPINE_DATABASE_URL
          value: "jdbc:postgresql://dev-dependency-track-database:5432/dependencytrack"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track-database
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track-backend
spec:
  template:
    spec:
      containers:
      - name: backend
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track-frontend
spec:
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: API_BASE_URL
          value: "http://dev-dependency-track-backend:8080"
