apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track-backend
  labels:
    app: dependency-track
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dependency-track
      component: backend
  template:
    metadata:
      labels:
        app: dependency-track
        component: backend
    spec:
      containers:
      - name: backend
        image: public.ecr.aws/a1x0e8q5/abdu/dt-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: ALPINE_DATABASE_MODE
          value: "external"
        - name: ALPINE_DATABASE_URL
          value: "jdbc:postgresql://dependency-track-database:5432/dependencytrack"
        - name: ALPINE_DATABASE_DRIVER
          value: "org.postgresql.Driver"
        - name: ALPINE_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: ALPINE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: ALPINE_DATA_DIRECTORY
          value: "/data"
        - name: JAVA_OPTIONS
          value: "-Xmx2g -Xms1g -XX:+UseG1GC"
        livenessProbe:
          httpGet:
            path: /api/version
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/version
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        volumeMounts:
        - name: data-volume
          mountPath: /data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: backend-data-pvc