apiVersion: v1
kind: Service
metadata:
  name: dependency-track-database
  labels:
    app: dependency-track
    component: database
spec:
  selector:
    app: dependency-track
    component: database
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  clusterIP: None  # Headless service for direct pod access