apiVersion: v1
kind: Service
metadata:
  name: dependency-track-database
  labels:
    app: dependency-track
    component: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: dependency-track
    component: database