apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: frontend

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: frontend
  tier: frontend
  
namespace: dependency-track