apiVersion: v1
kind: Service
metadata:
  name: dependency-track-frontend
  labels:
    app: dependency-track
    component: frontend
spec:
  type: LoadBalancer
  selector:
    app: dependency-track
    component: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP