apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
- ../../base

namePrefix: prod-
commonLabels:
  environment: prod

images:
- name: public.ecr.aws/a1x0e8q5/abdu/dt-frontend
  newTag: stable
- name: public.ecr.aws/a1x0e8q5/abdu/dt-backend
  newTag: stable

patchesStrategicMerge:
- patch.yaml

secretGenerator:
- name: database-secret
  behavior: replace
  literals:
  - username=dtuser
  - password=prod-secure-password-$(date +%s)

configMapGenerator:
- name: environment-config
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=INFO