apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend/
- backend/
- database/
- storage/persistentvolumeclaim.yaml
- secrets/secrets.yaml

labels:
- pairs:
    app: dependency-track
    managed-by: kustomize

images:
- name: public.ecr.aws/a1x0e8q5/abdu/dt-frontend
  newTag: latest
- name: public.ecr.aws/a1x0e8q5/abdu/dt-backend
  newTag: latest
- name: postgres
  newTag: 15-alpine